"""
Optional demo layer — a tiny Streamlit app so you can click through the
audit results interactively instead of just reading CSVs. Deliberately
minimal (one file, no backend/database) — this is a portfolio polish
touch, not infrastructure to defend in an interview.

Run: streamlit run src/app_streamlit.py
"""

import pandas as pd
import streamlit as st

import config

st.set_page_config(page_title="Chest X-ray Bias Audit", layout="wide")
st.title("Subgroup Bias Audit: Chest X-ray Classifier")
st.caption(
    "Explore how a multi-label CXR classifier's performance varies by "
    "sex, age group, and view position (AP vs PA)."
)

metrics_path = config.REPORTS_DIR / "subgroup_metrics.csv"
sig_path = config.REPORTS_DIR / "statistical_tests.csv"

if not metrics_path.exists():
    st.error(
        "No results found yet. Run the pipeline first: "
        "prepare_data.py -> train.py -> bias_analysis.py -> make_report.py"
    )
    st.stop()

metrics = pd.read_csv(metrics_path)
sig = pd.read_csv(sig_path)

finding = st.selectbox("Finding", sorted(metrics["finding"].unique()))
axis = st.selectbox("Subgroup axis", sorted(metrics["axis"].unique()))

filtered = metrics[(metrics["finding"] == finding) & (metrics["axis"] == axis)]

col1, col2 = st.columns([2, 1])
with col1:
    st.subheader(f"AUROC by {axis} for {finding}")
    st.bar_chart(filtered.set_index("subgroup")["AUROC"])
    st.dataframe(filtered[[
        "subgroup", "n_samples", "prevalence", "AUROC",
        "AUROC_CI_low", "AUROC_CI_high", "sensitivity", "specificity", "reliable"
    ]].round(3))
    st.caption(
        f"'reliable' = both classes have >= "
        f"{config.MIN_POSITIVES_FOR_RELIABLE_AUROC} samples in this subgroup. "
        "AUROC on unreliable subgroups can swing wildly on a single sample."
    )

with col2:
    st.subheader("Significance tests")
    sig_filtered = sig[(sig["finding"] == finding) & (sig["axis"] == axis)][[
        "group_a", "group_b", "gap", "p_value", "significant_p<0.05",
        "equalized_odds_gap", "reliable"
    ]].copy()
    # p_value can be the "<X" sentinel string (see bias_analysis.py's
    # permutation_test_gap) — once that's in the CSV, pandas reads the
    # *whole* p_value column as strings, not just those rows. Only round
    # the columns that are still guaranteed numeric.
    for col in ["gap", "equalized_odds_gap"]:
        sig_filtered[col] = sig_filtered[col].round(4)
    st.dataframe(sig_filtered)

st.divider()
st.subheader("Saliency map examples")
st.caption(
    "Generated by src/interpretability.py — compares what the model "
    "attends to on correct vs incorrect predictions."
)
fig_files = sorted(config.FIGURES_DIR.glob("saliency_*.png"))
if fig_files:
    cols = st.columns(4)
    for i, f in enumerate(fig_files):
        cols[i % 4].image(str(f), caption=f.name, use_column_width=True)
else:
    st.info("Run src/interpretability.py to generate saliency map figures.")
